[project]
name = "colbert-implementation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyterlab-quarto>=0.3.5",
    "nbdev>=2.3.31",
    "ruff>=0.6.8",
]
