# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/colbert-implementation',
                'doc_host': 'https://peterbull.github.io',
                'git_url': 'https://github.com/peterbull/colbert-implementation',
                'lib_path': 'colbert_implementation'},
  'syms': {'colbert_implementation.core': {'colbert_implementation.core.foo': ('core.html#foo', 'colbert_implementation/core.py')}}}
